CREATE DATABASE IF NOT EXISTS postdb;

USE postdb;

DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    userId INT UNSIGNED PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS posts
(
    postId INT UNSIGNED PRIMARY KEY,
    title VARCHAR(300) NOT NULL,
    body VARCHAR(500) NOT NULL,
    userId INT UNSIGNED,
    FOREIGN KEY (userId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS comments
(
    commId INT UNSIGNED PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(40),
    body VARCHAR(500),
    postId INT UNSIGNED,
    FOREIGN KEY (postId) REFERENCES posts(postId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
